# Generated by Django 4.2.6 on 2023-10-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(auto_created=True, blank=True, default=True, null=True),
        ),
    ]
