# Generated by Django 4.2.6 on 2023-11-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(auto_created=True, choices=[('pending', 'Pending'), ('read', 'Read')], default='pending', max_length=10),
        ),
    ]
