# Generated by Django 4.2.5 on 2023-09-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_id', models.CharField(max_length=15)),
                ('Serial_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stock_id', models.CharField(max_length=15)),
                ('Serial_no', models.CharField(max_length=15)),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
