# Generated by Django 4.2.7 on 2023-11-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pass_word',
            field=models.CharField(default='123456789', max_length=15),
        ),
    ]
