# Generated by Django 4.2.7 on 2023-11-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_assigned',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
