# Generated by Django 4.2.7 on 2024-03-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='workshop.district'),
        ),
    ]
