# Generated by Django 4.2.5 on 2023-09-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_component_item_delete_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
