# Generated by Django 4.2.6 on 2023-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(auto_created=True, choices=[('pending', 'pending'), ('on_prograss', 'On_progress'), ('completed', 'Completed'), ('Not maintainable', 'Not maintanable')], default='pending'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('Manager', 'manager'), ('Registeror', 'registeror'), ('Engineer', 'Engineer')], default='Engineer'),
        ),
    ]
