# Generated by Django 4.2.6 on 2023-10-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_component_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Repeat_Count',
        ),
        migrations.AddField(
            model_name='item',
            name='is_maintainable',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_accepted',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
