# Generated by Django 4.2.7 on 2023-11-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_user_pass_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pass_word',
            field=models.CharField(auto_created=True, default='123456789', max_length=15),
        ),
    ]
