# Generated by Django 4.2.6 on 2023-10-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_item_repeat_count_item_is_maintainable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='remark',
        ),
    ]
