# Generated by Django 3.2.6 on 2023-10-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_assignments_component_item_section_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
