# Generated by Django 4.2.7 on 2023-11-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_notification_link_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.assignments'),
        ),
    ]
