# Generated by Django 4.2.7 on 2024-03-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_item_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
