# Generated by Django 4.2.7 on 2023-11-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_user_pass_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='view_dashboard',
            field=models.BooleanField(auto_created=True, blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='view_item',
            field=models.BooleanField(auto_created=True, blank=True, default=False, null=True),
        ),
    ]
