# Generated by Django 3.2.6 on 2023-10-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_assignments_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='recived_date',
            field=models.DateField(auto_now=True),
        ),
    ]
