# Generated by Django 4.2.5 on 2023-09-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='engineer',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='item',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Assignments',
        ),
    ]
