# Generated by Django 4.2.6 on 2023-10-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_users_date_joined'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
