# Generated by Django 4.2.7 on 2023-11-19 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_user_view_dashboard_alter_user_view_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='workshop.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manage_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
