# Generated by Django 3.2.6 on 2023-10-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_component_recived_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.EmailField(max_length=50, unique=1),
        ),
    ]
