# Generated by Django 4.2.7 on 2023-11-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_item_section_alter_section_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pass_word',
            field=models.CharField(max_length=50),
        ),
    ]
