# Generated by Django 4.2.6 on 2023-10-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_item_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
