# Generated by Django 4.2.7 on 2024-03-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_user_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_approved',
            new_name='is_wh',
        ),
        migrations.AddField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(auto_created=True, blank=True, default=False, null=True),
        ),
    ]
