# Generated by Django 3.2.6 on 2023-10-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_auto_20231007_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
