# Generated by Django 4.2.7 on 2023-11-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workshop.assignments'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
