# Generated by Django 4.2.6 on 2023-10-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_alter_assignments_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(auto_created=True, choices=[('pending', 'pending'), ('on_prograss', 'On_progress'), ('completed', 'Completed')], default='pending'),
        ),
    ]
