# Generated by Django 4.2.7 on 2024-03-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_rename_is_approved_user_is_wh_item_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wh_comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
