# Generated by Django 4.2.6 on 2023-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_right_to_here',
            field=models.BooleanField(auto_created=True, default=True),
        ),
    ]
