# Generated by Django 4.2.7 on 2023-11-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_alter_user_pass_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='view_dashboard',
            field=models.BooleanField(auto_created=True, blank=True, default=True, null=True),
        ),
    ]
