# Generated by Django 4.2.7 on 2023-11-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(auto_created=True, choices=[('pending', 'pending'), ('on_progress', 'On_progress'), ('completed', 'Completed')], default='pending'),
        ),
    ]
