# Generated by Django 4.2.7 on 2023-11-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_alter_assignments_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.item'),
        ),
    ]
