# Generated by Django 4.2.7 on 2023-11-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_alter_assignments_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='district',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='received_by',
            new_name='delivered_by',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_maintainable',
            new_name='is_damage',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_right_to_here',
            new_name='is_maintainable_onfield',
        ),
    ]
