# Generated by Django 3.2.6 on 2023-10-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_assignments_component_item_section_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='completed_date',
            field=models.DateField(auto_created=True, default='2023-11-02'),
        ),
    ]
