# Generated by Django 4.2.7 on 2023-11-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='received_date',
            field=models.DateField(auto_created=True, auto_now=True, null=True),
        ),
    ]
