# Generated by Django 4.2.7 on 2023-11-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_rename_district_item_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_damage',
            field=models.BooleanField(auto_created=True, default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_maintainable_onfield',
            field=models.BooleanField(auto_created=True, default=False),
        ),
    ]
