# Generated by Django 3.2.6 on 2023-10-12 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0011_auto_20231011_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignments',
        ),
    ]
