# Generated by Django 4.2.7 on 2024-02-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_alter_item_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='remark',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='remark',
            field=models.TextField(),
        ),
    ]
