# Generated by Django 3.2.6 on 2023-10-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_delete_assignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('is_valid', models.BooleanField(auto_created=True, default=True)),
                ('completed_date', models.DateField(auto_created=True, default='2023-11-02')),
                ('as_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('remark', models.TextField(blank=True)),
                ('Assigned_date', models.DateField(auto_now=True)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.section')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.users')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.item')),
            ],
        ),
    ]
