# Generated by Django 4.2.7 on 2024-02-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_alter_assignments_remark_alter_item_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_stock', to='workshop.stock'),
        ),
    ]
