# Generated by Django 4.2.7 on 2024-02-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_alter_component_stock_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='Serial_no',
        ),
        migrations.AddField(
            model_name='component',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
