# Generated by Django 3.2.6 on 2023-10-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_auto_20231012_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_accepted',
            field=models.BooleanField(default=True),
        ),
    ]
