# Generated by Django 3.2.6 on 2023-10-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_alter_item_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
