# Generated by Django 4.2.6 on 2023-10-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='Repeat_Count',
            field=models.IntegerField(auto_created=True, default=1),
        ),
    ]
